
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title Groth16 verifier (stripped of Pedersen commitment infrastructure).
/// @notice Auto-generated by TestExportProofForFoundry. The Pedersen 2-pair pairing
/// check is removed because the circuit never uses Commit(). The commitment hash
/// (a constant) is folded into CONSTANT, saving ~119K gas.
contract Verifier {

    error PublicInputNotInField();
    error ProofInvalid();

    uint256 constant PRECOMPILE_MODEXP = 0x05;
    uint256 constant PRECOMPILE_ADD = 0x06;
    uint256 constant PRECOMPILE_MUL = 0x07;
    uint256 constant PRECOMPILE_VERIFY = 0x08;

    uint256 constant P = 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47;
    uint256 constant R = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001;

    uint256 constant ALPHA_X = 9588802445070275844852961003101536863434656841130503419190670018802291884958;
    uint256 constant ALPHA_Y = 6024024896807951010776339742531129946036156982587084874755920729940253481407;

    uint256 constant BETA_NEG_X_0 = 377876267968267164780869682441886312481751635850099960464014229158086200475;
    uint256 constant BETA_NEG_X_1 = 11077819320545516072619062334790083745418616952164496023352992820463582247383;
    uint256 constant BETA_NEG_Y_0 = 723619155438513663411399364264160342164158149159566913067531095692070660683;
    uint256 constant BETA_NEG_Y_1 = 608248107560583823911521924486556103960375511721525435490038284291244518566;

    uint256 constant GAMMA_NEG_X_0 = 10227885253030166601982817748001525981750636147386802837651929900796612165871;
    uint256 constant GAMMA_NEG_X_1 = 16869371677529218931005706691429058783084219645543053355257813077227542323058;
    uint256 constant GAMMA_NEG_Y_0 = 448876961080056991918311643263092625523192758643722248402879593587387720922;
    uint256 constant GAMMA_NEG_Y_1 = 15436630780955539822001124059923848595172454281965898506086614816649722951832;

    uint256 constant DELTA_NEG_X_0 = 1801104455035864888300581939557074253205705379515825764650863653835231490171;
    uint256 constant DELTA_NEG_X_1 = 4516182729753191743289719462436920902786953439051059706506910229967485869317;
    uint256 constant DELTA_NEG_Y_0 = 10699616502501990558857707683801277874542321475117855314536529836129366780864;
    uint256 constant DELTA_NEG_Y_1 = 17096443909637364825473709759468400412434570989473194924833700863105810402508;

    // Folded constant: original CONSTANT + PUB_1 * keccak256(commitment=(0,0)) % R
    uint256 constant CONSTANT_X = 1117097502622001246680032322457414841417829158576975807530266653035628405694;
    uint256 constant CONSTANT_Y = 19221879280104699569524038618984225740967839716888476518457378938785696463666;
    uint256 constant PUB_0_X = 1205183996061975728445623069134577160689118929742105786948830806560079286142;
    uint256 constant PUB_0_Y = 11233688628017510737674805804364642476197514185405845782016612989533129003312;

    function publicInputMSM(uint256[1] calldata input)
    internal view returns (uint256 x, uint256 y) {
        bool success = true;
        assembly ("memory-safe") {
            let f := mload(0x40)
            let g := add(f, 0x40)
            let s
            mstore(f, CONSTANT_X)
            mstore(add(f, 0x20), CONSTANT_Y)
            mstore(g, PUB_0_X)
            mstore(add(g, 0x20), PUB_0_Y)
            s := calldataload(input)
            mstore(add(g, 0x40), s)
            success := and(success, lt(s, R))
            success := and(success, staticcall(gas(), PRECOMPILE_MUL, g, 0x60, g, 0x40))
            success := and(success, staticcall(gas(), PRECOMPILE_ADD, f, 0x80, f, 0x40))
            x := mload(f)
            y := mload(add(f, 0x20))
        }
        if (!success) {
            revert PublicInputNotInField();
        }
    }

    function verifyProof(
        uint256[8] calldata proof,
        uint256[1] calldata input
    ) public view {
        (uint256 x, uint256 y) = publicInputMSM(input);

        bool success;
        assembly ("memory-safe") {
            let f := mload(0x40)
            calldatacopy(f, proof, 0x100)
            mstore(add(f, 0x100), DELTA_NEG_X_1)
            mstore(add(f, 0x120), DELTA_NEG_X_0)
            mstore(add(f, 0x140), DELTA_NEG_Y_1)
            mstore(add(f, 0x160), DELTA_NEG_Y_0)
            mstore(add(f, 0x180), ALPHA_X)
            mstore(add(f, 0x1a0), ALPHA_Y)
            mstore(add(f, 0x1c0), BETA_NEG_X_1)
            mstore(add(f, 0x1e0), BETA_NEG_X_0)
            mstore(add(f, 0x200), BETA_NEG_Y_1)
            mstore(add(f, 0x220), BETA_NEG_Y_0)
            mstore(add(f, 0x240), x)
            mstore(add(f, 0x260), y)
            mstore(add(f, 0x280), GAMMA_NEG_X_1)
            mstore(add(f, 0x2a0), GAMMA_NEG_X_0)
            mstore(add(f, 0x2c0), GAMMA_NEG_Y_1)
            mstore(add(f, 0x2e0), GAMMA_NEG_Y_0)
            success := staticcall(gas(), PRECOMPILE_VERIFY, f, 0x300, f, 0x20)
            success := and(success, mload(f))
        }
        if (!success) {
            revert ProofInvalid();
        }
    }
}
